name: base
channels:
        - pyviz
        - conda-forge
        - defaults
          #- rapidsai
dependencies:
        - bottleneck
        - bqplot
        - cython
        - category_encoders
        - dask
        - dask-ml  
        - dask_labextension
        - dask-xgboost
          ##- rapidsai::dask-cuda
          #- pytorch::pytorch
          #- descartes
        - feather-format
        - joblib
        - intake
        - intake-geopandas
        - intake-xarray
        - intake-stac
        - intake-thredds
        - intake-parquet 
        - ipython
        - ipywidgets
        - jupyter
        - jupyterlab=2
          #- bokeh
          #- jupyter_bokeh
        - matplotlib
        - netCDF4  
        - nodejs
        - numpy
        - pandas
        - pyarrow
        - pygeos
        - proplot
        - requests
        - seaborn
        - scipy
        - pymc3
        - scikit-learn
        - statsmodels
        - urllib3
        - xarray
        - xarray-spatial
        - rioxarray
        - geopandas
        - pyviz::geoviews  
        - xgboost
        - lightgbm
        ## - rapidsai::rapids
        - hvplot
        - imgaug
        - albumentations
        - pip  
        - pip:
                - kornia
                - nbdev
                - wandb
                - torchvision #==0.6.1
                - pytorch-lightning
                - pytorch-lightning-bolts  
                - pytorch-forecasting 
                - skorch
                - geffnet
                  #- git+https://github.com/facebookresearch/fvcore
                  #- git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
                  #- git+https://github.com/facebookresearch/detectron2
                - git+https://github.com/rapidsai/jupyterlab-nvdashboard
                - fastprogress
                - dtreeviz
                - bokeh
                - jupyter-bokeh

