name: base
channels:
        - conda-forge
        - defaults
dependencies:
        - dvc-s3
        - ipython
        - ipywidgets
        - jupyter
        - jupyterlab=3
        - dask
        - dask-ml
        - dask-xgboost
        - feather-format
        - joblib
        - intake
        - intake-geopandas
        - intake-xarray
        - intake-thredds
        - intake-parquet  
        - bottleneck
        - netCDF4  
        - numpy
        - pandas
        - panel
        - pyarrow
        - pygeos
        - proplot
        - requests
        - seaborn
        - scipy
        - pymc3
        - scikit-learn
        - statsmodels
        - urllib3
        - xarray
        - gdal
        - rasterio
        - rioxarray
        - geopandas
        - geoviews
        - xgboost
        - lightgbm
        - hvplot
        - imgaug
        - albumentations
        - pip  
        - pip:
                - jupyterlab_nvdashboard
                - dask-labextension
                - pyviz_comms
                - monai
                - kornia
                - wandb
                - pytorch-lightning
                - pytorch-forecasting 

